version: '3.8'

services:
  db:
    image: postgres:16.6
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"  # Пароль в кавычках, если содержит цифры
      POSTGRES_DB: rushydro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rushydro"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - selenium-network

  backend:
    build:
      context: ./backEnd  # Путь к папке с Dockerfile бэкенда
    ports:
      - "8081:8081"  # Пробрасываем порт бэкенда
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:p6spy:postgresql://db:5432/rushydro"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "123"
    networks:
      - selenium-network

  frontend:
    build:
      context: ./front  # Путь к папке с Dockerfile фронтенда
    container_name: front
    ports:
      - "8080:8080"  # Пробрасываем порт фронтенда
    depends_on:
      - backend  # Фронтенд запустится только после бэкенда
    restart: unless-stopped
    networks:
      - selenium-network

  selenium-hub:
#    image: selenium/hub:4.15.0
    image: selenium/hub:4.31.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - selenium-network

  chrome:
#    image: selenium/node-chrome:4.15.0
    image: selenium/node-chrome:4.31.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      selenium-hub:
        condition: service_healthy
    networks:
      - selenium-network

  autocrawling:
    build:
      context: ./autoCrawling  # Изменено на папку autoCrawling
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge

volumes:
  postgres_data: