version: '3.8'

services:
  # Бэкенд (Spring Boot)
  backend:
    image: openjdk:17-jdk-slim  # Или ваша кастомная сборка
    container_name: backend
    build:
      context: ./backend  # Путь к папке с Dockerfile бэкенда
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Пробрасываем порт 8081 наружу
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
    volumes:
      - ./backend/data:/app/data  # Если нужно хранить данные
    networks:
      - app-network

  # Фронтенд (Nginx для статики)
  frontend:
    image: nginx:alpine
    container_name: frontend
    build:
      context: ./frontend  # Путь к папке с Dockerfile фронтенда
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Nginx слушает на 80, пробрасываем на 8080
    volumes:
      - ./frontend/dist:/usr/share/nginx/html  # Монтируем собранный фронтенд
    depends_on:
      - backend
    networks:
      - app-network

# Общая сеть для связи контейнеров
networks:
  app-network:
    driver: bridge