version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"  # Пароль в кавычках, если содержит цифры
      POSTGRES_DB: rushydro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rushydro"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backEnd  # Путь к папке с Dockerfile бэкенда
    ports:
      - "8081:8081"  # Пробрасываем порт бэкенда
    depends_on:
      db:
        condition: service_healthy
    environment:  # Правильное форматирование environment
      SPRING_DATASOURCE_URL: "jdbc:p6spy:postgresql://db:5432/rushydro"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "123"  # Всегда в кавычках!

  frontend:
    build:
      context: ./front  # Путь к папке с Dockerfile фронтенда
#      dockerfile: Dockerfile  # Или укажите другой файл, если нужно
    container_name: front
    ports:
      - "8080:8080"  # Пробрасываем порт фронтенда
    depends_on:
      - backend  # Фронтенд запустится только после бэкенда
    restart: unless-stopped

volumes:
  postgres_data: